services:
  mediators:
    build:
      context: .
    ports:
      - "192.168.0.119:8002:8002"
    volumes:
      - ./mediators:/mediators
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8002"
    container_name: mediators-test
    restart: unless-stopped
